### ISSUE TITLE
Crash when break blocks

### ISSUE THREAD

**Issue by scottosx** [kitsushadow/forgecraft#11]
Crash log when picking up bellows:

[crash-2017-05-16_12.01.09-client.txt](https://github.com/kitsushadow/forgecraft/files/1005274/crash-2017-05-16_12.01.09-client.txt)

Crash log when breaking stone anvil:

[crash-2017-05-16_12.12.05-client.txt](https://github.com/kitsushadow/forgecraft/files/1005276/crash-2017-05-16_12.12.05-client.txt)

**Comment by kitsushadow** [comment]
Thanks for the bug report i think i know what it is. Been looking for that
bug to present itself again. Ill give it a look tonight

**Comment by kitsushadow** [comment]
Pushed a new version on curse @scottosx 
1.2.22
Please let me know if this new version resolves this. Thanks

**Comment by kitsushadow** [comment]
Closing this issue.
