### ISSUE TITLE
[1.11.2] Crash clicking toolpart in JEI

### ISSUE THREAD

**Issue by Silvrus** [kitsushadow/forgecraft#13]
Clicking the iron pick head in JEI caused this crash https://pastebin.com/EAfPazd8

**Comment by kitsushadow** [comment]
what Forgecraft version are u using?

**Comment by Silvrus** [comment]
Sorry, thought that was in the report.

Forge 13.20.0.2312

**Comment by kitsushadow** [comment]
ya i found it, did you click on the JEI anvil icon? or did it not even open
a gui?

i partially recreated this by looking in jei for the toolhead and then
click it, jei opened something but upon clicking the anvil i crashed

**Comment by Silvrus** [comment]
Clicked on the JEI pickhead icon and got no gui, just crash. Updated to .2315 and it seems to be fixed.

That being said, how do you get the pickhead off the anvil?

**Comment by Silvrus** [comment]
Correction, just clicked on the anvil icon and it crashed as well. Same crash report.

**Comment by kitsushadow** [comment]
if it turns cool you should be able to use an empty hand to remove it
if it is still hot use the tongs

make sure u are aiming at the anvil grid position, not the rendered item

**Comment by kitsushadow** [comment]
i'm removing the tool head from the creative tab

**Comment by kitsushadow** [comment]
I uploaded a new beta version. try that out. it should not be crashable now

**Comment by Silvrus** [comment]
Ok cool, I'll grab it. 

For the pickhead, it doesn't appear to be cooling into the actual pickhead form, just staying in the hot iron chunks.

**Comment by Silvrus** [comment]
Now I get this crash: https://pastebin.com/ycWBMiUe

**Comment by kitsushadow** [comment]
That will be fixed with the next Primal Release
