### ISSUE TITLE
Crash on loading screen.

### ISSUE THREAD

**Issue by Titus-Armillius** [kitsushadow/forgecraft#14]
Crash report: https://pastebin.com/8mkhbvgj

The crash contains my mod list just in case you were wondering. 

My guess is that it's a crash with CustomStuff4, maybe not.

**Comment by kitsushadow** [comment]
something about BetterGrass update method

**Comment by Titus-Armillius** [comment]
@kitsushadow So do you thinks its optifine?

**Comment by kitsushadow** [comment]
my first guess is better foliage

**Comment by Titus-Armillius** [comment]
@kitsushadow Turns out it was that I was using the wrong forge version, but some mod change the crash error.

**Comment by kitsushadow** [comment]
ah, that'll get ya
