### ISSUE TITLE
[1.11.2 1.2.71] Can't get bloomery hot enough 

### ISSUE THREAD

**Issue by Ryusabre** [kitsushadow/forgecraft#15]
So, for whatever reason, I can't get the bloomery to reach 2000 degrees. I can get up to 1600, sometimes 1650, before the bloomery resets down to 1200. This is usually accompanied by a sound like air escaping, but nothing else, as far as I can tell.

I can understand having the bloomery cool down over time, and even have it be harder to reach higher temperatures, but considering the first item you craft in a bloomery requires 2000 degrees, having such a hard cutoff seems unintended.

**Comment by kitsushadow** [comment]
U need to use a higher quality charcoal than vanilla charcoal,

good quality charcoal will have a max temp capable of meeting that temperature requirement

**Comment by Ryusabre** [comment]
That was it. The wiki never mentioned charcoal quality, so I didn't consider that when testing my pack. Thanks for the quick reply.
