### ISSUE TITLE
Bloomery using coal too quickly

### ISSUE THREAD

**Issue by Mattrock607** [kitsushadow/forgecraft#16]
Fair, good, and high grade coal is burning at an accelerated rate in the adobe and brick bloomeries. A full stack of coal burns very quickly and seems to burn several units at a time when using a piston bellows. 

MC Version: 1.12
Forge Version: 1.12-14.21.1.2443
Mod Version: 1.3.1
Mode: Creative, superflat world

![2017-09-03_22 47 53](https://user-images.githubusercontent.com/13137808/30009936-3224ce8e-90fa-11e7-9ae5-2dd3642a016f.png)

**Comment by kitsushadow** [comment]
should be fixed, releasing 1.3.2 for testing
