### ISSUE TITLE
Minor aesthetic issue: class/ short names showing for some items

### ISSUE THREAD

**Issue by Mattrock607** [kitsushadow/forgecraft#17]
Class/ short names are showing in the creative inventory for the following items:

item.brokenbronzetool.name
item.brokenwroughtirontool.name
item.brokencleanirontool.name
item.brokensteeltool.name
item.brokenwootztool.name
item.wootzingotballhot.name
tile.failedcleanironcruciblehot.name

MC Version: 1.12
Forge Version: 1.12-14.21.1.2443
Mod Version: 1.3.1
Mode: Creative, superflat world

**Comment by kitsushadow** [comment]
this is expected
