### ISSUE TITLE
Minor aesthetic issue: Textures not appearing for two items

### ISSUE THREAD

**Issue by Mattrock607** [kitsushadow/forgecraft#18]
Textures are not appearing for the following items (they appear in the creative menu as purple/ black squares):

item.wootzingotballhot.name
Hot Damascus Steel Chunk

MC Version: 1.12
Forge Version: 1.12-14.21.1.2443
Mod Version: 1.3.1
Mode: Creative, superflat world

**Comment by kitsushadow** [comment]
this is expected
