### ISSUE TITLE
Anvils breaking strangely/ easily

### ISSUE THREAD

**Issue by Mattrock607** [kitsushadow/forgecraft#19]
Both stone and iron anvils are breaking with a single right-click from a forge hammer or a gallhager when they contain any formation of hot iron chunks. Tested in both creative and survival modes. I don't know if this is a bug but smacking a cooled iron ingot with the gallhager produces hot iron chunks.

MC Version: 1.12
Forge Version: 1.12-14.21.1.2443
Mod Version: 1.3.1
Mode: Creative/ survival, superflat world

**Comment by kitsushadow** [comment]
should be fixed, releasing 1.3.2 for testing
