### ISSUE TITLE
FYI/Crash Report

### ISSUE THREAD

**Issue by Nexusdog** [kitsushadow/forgecraft#21]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.2-104.jar)
  FarseekCoreMod (Farseek-1.12-2.2.jar)
  RBLoadingPlugin (RealBench-1.12-1.3.3.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.7.1.jar)
  BCModPlugin (backpacks 1.12 - 3.3.0.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  LoadingPlugin (RandomThings-MC1.12.1-4.0.5.jar)
  DummyPlugin (ForgeEndertech-1.12-3.0.1.0-build.0012.jar)
  MalisisSwitchesPlugin (malisisswitches-1.12-5.0.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+dev.94.jar)
  llibrary (llibrary-1.7.7-1.12.jar)
  MalisisCorePlugin (malisiscore-1.12-6.0.4.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.2.7.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  MovingWorldCoreMod (movingworld-1.12-5.341-full.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 9/16/17 3:54 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Kitsu's Forgecraft (forgecraft)
Caused by: java.lang.NoClassDefFoundError: nmd/primal/core/api/PrimalStates
	at nmd.primal.forgecraft.blocks.Forge.func_180661_e(Forge.java:414)
	at net.minecraft.block.Block.<init>(Block.java:234)
	at net.minecraft.block.BlockContainer.<init>(SourceFile:28)
	at net.minecraft.block.BlockContainer.<init>(SourceFile:24)
	at nmd.primal.forgecraft.blocks.CustomContainerFacing.<init>(CustomContainerFacing.java:18)
	at nmd.primal.forgecraft.blocks.Forge.<init>(Forge.java:54)
	at nmd.primal.forgecraft.init.ModBlocks.init(ModBlocks.java:121)
	at nmd.primal.forgecraft.ForgeCraft.preInit(ForgeCraft.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:614)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: nmd.primal.core.api.PrimalStates
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 48 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 10615247336 bytes (10123 MB) / 12596019200 bytes (12012 MB) up to 12596019200 bytes (12012 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12g -Xms12g
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2443 117 mods loaded, 117 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2443.jar) 
	UCH	forge{14.21.1.2443} [Minecraft Forge] (forge-1.12-14.21.1.2443.jar) 
	UCH	ivtoolkit{1.3.3-1.12} [IvToolkit] (minecraft.jar) 
	UCH	com.elytradev.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCH	backpacks16840{3.3.0} [Backpacks!] (backpacks 1.12 - 3.3.0.jar) 
	UCH	simplebedrolls{1.2.1} [Simple Bedrolls] ([1.12]SimpleBedrolls-1.2.1.jar) 
	UCH	uncraftingtable{1.8-beta5} [Uncrafting Table] ([1.12]UncraftingTable-1.8-beta5.jar) 
	UCH	jei{4.7.8.95} [Just Enough Items] (jei_1.12.1-4.7.8.95.jar) 
	UCH	abyssalcraft{1.9.4-pre-4} [AbyssalCraft] (AbyssalCraft-1.12-1.9.4-pre-4.jar) 
	UCH	chisel{MC1.12-0.0.13.16} [Chisel] (Chisel-MC1.12-0.0.13.16.jar) 
	UCH	mantle{1.12-1.3.1.21} [Mantle] (Mantle-1.12-1.3.1.21.jar) 
	UCH	tconstruct{1.12-2.7.3.30} [Tinkers' Construct] (TConstruct-1.12-2.7.3.30.jar) 
	UCH	acintegration{1.5.0} [AbyssalCraft Integration] (AbyssalCraft Integration-1.12-1.5.0.jar) 
	UCH	actuallyadditions{1.12.1-r119} [Actually Additions] (ActuallyAdditions-1.12.1-r119.jar) 
	UCH	baubles{1.5.1} [Baubles] (Baubles-1.12-1.5.1.jar) 
	UCH	actuallybaubles{1.1} [Actually Baubles] (ActuallyBaubles-1.12-1.1.jar) 
	UCH	allthedrops{1.0.1} [All the Drops] (allthedrops-1.11.2-1.0.1-build-T22.jar) 
	UCH	architecturecraft{@VERSION@} [ArchitectureCraft] (architecturecraft-1.12-1.20.jar) 
	UCH	quark{r1.2-104} [Quark] (Quark-r1.2-104.jar) 
	UCH	autoreglib{1.3-13} [AutoRegLib] (AutoRegLib-1.3-13.jar) 
	UCH	betterbedrockgen{6.0.2} [BetterBedrockGen] (BetterBedrockGenerator-1.12-6.1.1.jar) 
	UCH	betterunderground{1.0.1} [Better Underground] (betterunderground-1.0.1.jar) 
	UCH	bibliocraft{2.4.3} [BiblioCraft] (BiblioCraft[v2.4.3][MC1.12.0].jar) 
	UCH	biomesoplenty{7.0.0.2289} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2289-universal.jar) 
	UCH	birdsnests{2.0.0} [Bird's Nests] (BirdsNests1.12-2.0.0.jar) 
	UCH	bookshelf{2.1.436} [Bookshelf] (Bookshelf-1.12.1-2.1.436.jar) 
	UCH	clarity{1.0} [Clarity] (clarity-1.0.jar) 
	UCH	cleanview{1.10.2-v1} [CleanView] (CleanView-1.10.2-v1.jar) 
	UCH	clockhud{1.4.0} [Clock HUD] (ClockHUD-1.12-1.4.0.jar) 
	UCH	cyclopscore{0.10.17} [Cyclops Core] (CyclopsCore-1.12-0.10.17.jar) 
	UCH	commoncapabilities{1.4.0} [CommonCapabilities] (CommonCapabilities-1.12-1.4.0.jar) 
	UCH	concreteplus{1.1.2} [Concrete Extends] (ConcreteExtends-1.1.2_1.12.jar) 
	UCH	ctm{MC1.12-0.2.2.7} [CTM] (CTM-MC1.12-0.2.2.7.jar) 
	UCH	customizeddungeonloot{1.0.1} [§eCustomized Dungeon Loot] (Customized Dungeon Loot (v.1.0.1).jar) 
	UCH	cyclicmagic{1.8.3} [Cyclic] (Cyclic-1.12-1.8.3.jar) 
	UCH	waila{1.8.20} [Waila] (Hwyla-1.8.20-B35_1.12.jar) 
	UCH	darkutils{1.7.169} [Dark Utilities] (DarkUtils-1.12.1-1.7.169.jar) 
	UCH	movingworld{1.12-5.341} [Moving World] (movingworld-1.12-5.341-full.jar) 
	UCH	davincisvessels{@DVESSELSVER@} [Davinci's Vessels] (davincisvessels-1.12-5.335-full.jar) 
	UCH	gottschcore{1.1.2} [GottschCore] (GottschCore-mc1.12-v1.1.2.jar) 
	UCH	dungeons2{1.3.1} [Dungeons2!] (Dungeons2-mc1.12-v1.3.1.jar) 
	UCH	dsurround{3.4.7.1} [Dynamic Surroundings] (DynamicSurroundings-1.12-3.4.7.1.jar) 
	UCH	presets{3.4.7.1} [Presets!] (DynamicSurroundings-1.12-3.4.7.1.jar) 
	UCH	earthworks{1.3.4.3} [Earthworks] (Earthworks-1.12-1.3.4.3.jar) 
	UCH	elevatorid{1.3.4} [Elevator Mod] (ElevatorMod-1.12-1.3.4.jar) 
	UCH	csb_ench_table{1.1.2} [Lapis Stays in the Enchanting Table] (EnchantingTable-1.12-1.1.2.jar) 
	UCH	enchdesc{1.0.4} [Enchantment Descriptions] (EnchantmentDescriptions-1.12-1.0.4.jar) 
	UCH	everlastingabilities{1.3.3} [EverlastingAbilities] (EverlastingAbilities-1.12-1.3.3.jar) 
	UCH	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.12-1.6.1.jar) 
	UCH	farseek{2.2} [Farseek] (Farseek-1.12-2.2.jar) 
	UCH	fastleafdecay{v13} [Fast Leaf Decay] (FastLeafDecay-v13.jar) 
	UCH	flatcoloredblocks{mc1.12-6.5} [Flat Colored Blocks] (flatcoloredblocks-mc1.12-6.5.jar) 
	UCH	natura{1.12-4.3.0.16} [Natura] (Natura-1.12-4.3.0.16.jar) 
	UCH	forestry{5.5.5.192} [Forestry] (forestry_1.12.1-5.5.5.192.jar) 
	UCH	primal{0.5.11} [PrimalCore] (PrimalCore-1.12.1-0.5.11.jar) 
	UCE	forgecraft{1.3.22} [Kitsu's Forgecraft] (ForgeCraft-1.3.22.jar) 
	UCH	forgeendertech{1.12-3.0.1.0} [Forge Endertech] (ForgeEndertech-1.12-3.0.1.0-build.0012.jar) 
	UCH	friendlyfire{1.5.5} [Friendly Fire] (FriendlyFire-1.12-1.5.5.jar) 
	UCH	silentlib{2.2.7} [Silent Lib] (SilentLib-1.12-2.2.7-85.jar) 
	UCH	funores{1.5.7} [Fun Ores] (FunOres-1.12-1.5.7-117.jar) 
	UCH	gamestages{1.0.62} [Game Stages] (GameStages-1.12.1-1.0.62.jar) 
	UCH	gravelminer{6.1.2} [GravelMiner] (GravelMiner_1.12.1-6.1.2.jar) 
	UCH	tombstone{1.3.7} [Corail Tombstone] (tombstone-1.3.7-1.12.jar) 
	UCH	gravestone{1.0.12} [Gravestone] (GraveStone-1.12-Graves-1.0.12.jar) 
	UCH	guideapi{1.12-2.1.4-57} [Guide-API] (Guide-API-1.12-2.1.4-57.jar) 
	UCH	harshencastle{0.9.4} [Harshen Castle] (harshencastle-0.9.4.jar) 
	UCH	iv{3.0.2} [Improved Villagers] (Improved Villagers-3.0.2.jar) 
	UCH	improvedbackpacks{1.12-1.1.2.0} [Improved Backpacks] (ImprovedBackpacks-1.12-1.1.2.0.jar) 
	UCH	inventorytweaks{1.63+dev.94.3cdd29e} [Inventory Tweaks] (InventoryTweaks-1.63+dev.94.jar) 
	UCH	itemscroller{0.11.0} [Item Scroller] (itemscroller-1.12.0-0.11.0.jar) 
	UCH	jeibees{0.9.0.4} [JEI Bees] (jeibees-0.9.0.4-mc1.12.1.jar) 
	UCH	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCH	levelup2{${version}} [Level Up! Reloaded] (Level Up! 2-1.1.1-1.12.jar) 
	UCH	llibrary{1.7.7} [LLibrary] (llibrary-1.7.7-1.12.jar) 
	UCH	malisiscore{1.12-6.0.4} [MalisisCore] (malisiscore-1.12-6.0.4.jar) 
	UCH	malisisblocks{1.12-6.0.2} [Malisis Blocks] (malisisblocks-1.12-6.0.2.jar) 
	UCH	malisisdoors{1.12-7.0.4} [MalisisDoors] (malisisdoors-1.12-7.0.4.jar) 
	UCH	malisisswitches{1.12-5.0.0} [Malisis Switches] (malisisswitches-1.12-5.0.0.jar) 
	UCH	mobfarm{2.2.1} [Mob Farm] (Mob Farm-1.12-2.2.1.jar) 
	UCH	mob_grinding_utils{0.3.2} [mob_grinding_utils] (MobGrindingUtils-0.3.2.jar) 
	UCH	modernlamps{1.0.3} [Modern Lights] (ModernLights-1.0.3_1.12.jar) 
	UCH	moreloottables{0.1.0} [More Loot Tables] (moreloottables-1.12.0-0.1.0.jar) 
	UCH	moreoverlays{1.12} [MoreOverlays] (moreoverlays-1.12-mc1.12.jar) 
	UCH	recipehandler{0.9} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.9(1.12).jar) 
	UCH	redstoneflux{2.0.1} [Redstone Flux] (RedstoneFlux-1.12-2.0.1.2-universal.jar) 
	UCH	notenoughwands{1.5.9} [Not Enough Wands] (notenoughwands-1.12-1.5.9.jar) 
	UCH	oreberries{0.2.0} [Oreberries] (oreberries-1.12.x-0.2.0.jar) 
	UCH	oreshrubs{1.4.0} [Ore Shrubs] (oreshrubs-1.4.0-1.12.jar) 
	UCH	jp.crafterkina.pipes{1.1.0.15} [Pipes] (Pipes-1.12-1.1.0.15.jar) 
	UCH	randomthings{4.0.5} [Random Things] (RandomThings-MC1.12.1-4.0.5.jar) 
	UCH	randomtweaks{1.12.1-1.10.0.1} [RandomTweaks] (randomtweaks-1.12.1-1.10.0.1.jar) 
	UCH	reccomplex{1.4.5} [Recurrent Complex] (RecurrentComplex-1.4.5.jar) 
	UCH	redstonepaste{1.7.5} [Redstone Paste] (redstonepaste-mc1.12-1.7.5.jar) 
	UCH	ruins{16.9} [Ruins Mod] (Ruins-1.12.jar) 
	UCH	woodenshears{@MAJOR@.@MINOR@.@REVIS@.@BUILD@} [Wooden Shears] (SBM-WoodenShears-1.12-0.0.1b7.jar) 
	UCH	icc{0.2.2} [Simple Item Collector Chest] (Simple Item Collector Chest-0.2.2.jar) 
	UCH	simpleleather{1.12-1.0} [Simple Leather] (simpleleather-1.12-1.0.jar) 
	UCH	soundfilters{0.10_for_1.12} [Sound Filters] (SoundFilters-0.10_for_1.12.jar) 
	UCH	spawnercraft{4.0.0} [SpawnerCraft] (SpawnerCraft 1.12-4.0.0.jar) 
	UCH	streams{0.4} [Streams] (Streams-1.12-0.4.jar) 
	UCH	tinkertoolleveling{1.12-1.0.2b.DEV.1a79301} [Tinkers Tool Leveling] (TinkerToolLeveling-1.12-1.0.2b.jar) 
	UCH	muchmorechickens{1.7} [muchmorechickens] (TMC-1.12-1.7.jar) 
	UCH	toolbelt{1.7.1} [Tool Belt] (ToolBelt-1.12.0-1.7.1.jar) 
	UCH	treechopper{1.2.2} [Tree Chopper] (TreeChopper-1.12-1.2.2.jar) 
	UCH	uncrafted{3.0.1} [Uncrafted] (Uncrafted 1.12  (v.3.0.1).jar) 
	UCH	veinminer{0.38.1} [Vein Miner] (VeinMiner-1.12-0.38.1.639+134fb1e.jar) 
	UCH	veinminermodsupport{0.38.1} [Mod Support] (VeinMiner-1.12-0.38.1.639+134fb1e.jar) 
	UCH	vc{5.0.6} [ViesCraft] (ViesCraft-1.12.0-5.0.6.jar) 
	UCH	villagermarket{1.0} [Villager Market] (villagermarket-0.2-HF.jar) 
	UCH	vtt{0.6.4} [Villager Trade Tables] (VillagerTrades-1.12-0.6.4.jar) 
	UCH	wailaharvestability{1.1.11} [Waila Harvestability] (WailaHarvestability-mc1.12-1.1.11.jar) 
	UCH	wawla{2.5.243} [What Are We Looking At] (Wawla-1.12.1-2.5.243.jar) 
	UCH	waystones{4.0.15} [Waystones] (Waystones_1.12.1-4.0.15.jar) 
	UCH	ironic_wdt{1.0} [Weak Drop Tweaks] (WeaKDropTweaks-1.0.jar) 
	UCH	wearables{1.1.2} [Wearables] (wearables-1.1.2.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.2-104.jar)
  vazkii.quark.base.asm.ClassTransformer
FarseekCoreMod (Farseek-1.12-2.2.jar)
  farseek.core.FarseekClassTransformer
RBLoadingPlugin (RealBench-1.12-1.3.3.jar)
  pw.prok.realbench.asm.RBTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.7.1.jar)
  org.blockartistry.DynSurround.asm.Transformer
BCModPlugin (backpacks 1.12 - 3.3.0.jar)
  brad16840.common.asm.ClassTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
LoadingPlugin (RandomThings-MC1.12.1-4.0.5.jar)
  lumien.randomthings.asm.ClassTransformer
DummyPlugin (ForgeEndertech-1.12-3.0.1.0-build.0012.jar)
  
MalisisSwitchesPlugin (malisisswitches-1.12-5.0.0.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63+dev.94.jar)
  invtweaks.forge.asm.ContainerTransformer
llibrary (llibrary-1.7.7-1.12.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
MalisisCorePlugin (malisiscore-1.12-6.0.4.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
CTMCorePlugin (CTM-MC1.12-0.2.2.7.jar)
  team.chisel.ctm.client.asm.CTMTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
MovingWorldCoreMod (movingworld-1.12-5.341-full.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13492 Compatibility Profile Context 22.19.676.0' Renderer: 'AMD Radeon (TM) R7 370 Series'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

**Comment by kitsushadow** [comment]
thanks for the report, working through it.

**Comment by kitsushadow** [comment]
I wasn't able to replicate this but it my dazed sick state i may not have version bumped last night and released a bad version. 

I have double checked the forge this morning and it works just fine. Make sure you have the newest version of Primal when trying version ForgeCraft-1.3.23

**Comment by Nexusdog** [comment]
Okay mate thanks for the reply. 
PrimalCore-1.12.1-0.5.11.jar
ForgeCraft-1.3.23

MC has hissy fit on loading

https://pastebin.com/eAWrmt1e

Definitely doesn't like another mod I running, cos I can't see it being a tantrum between PC & FC. Ruins, maybe?

**Comment by kitsushadow** [comment]
Just released ForgeCraft-1.3.24. It should fix your errors.

**Comment by Nexusdog** [comment]
Cheers matey! Big slobbery kiss :-)
