### ISSUE TITLE
Caught exception from Kitsu's Forgecraft (forgecraft)

### ISSUE THREAD

**Issue by ExplodingNova** [kitsushadow/forgecraft#22]
I got this crash; https://pastebin.com/uT9fhdE8
When I first got the crash, I kept removing mods (thinking it was a compatibility problem) until it was just Forgecraft and Primalcore, and it still crashed. I have the latest version of each mod.

**Comment by kitsushadow** [comment]
Found what's going on. Sorting it out.

Thanks for the report

**Comment by Ash70** [comment]
In case it helps, I have the same crash so [here's my log](https://pastebin.com/fwcmZeWX).

**Comment by kitsushadow** [comment]
Just released ForgeCraft-1.3.24. It should fix your errors.

**Comment by darthvader45** [comment]
Found this in the latest release for 1.12.2, 1.4.08 with RecipeHandler.  I'll try going back a version or two to see if this fixes it.  If not, this will be a major bug.
