### ISSUE TITLE
No recipe for iron dust.

### ISSUE THREAD

**Issue by CJL48** [kitsushadow/forgecraft#26]
When playing this mod without another mod that adds machines/recipes for iron dust installed, there is as far as I can tell, no way to create iron dust, preventing me from creating clean iron or steel.

Versions/Mods installed:
Minecraft 1.12.2
Forge 14.23.0.2491
Primalcore 0.5.12
Kitsu's Forgecraft 1.3.24
Just Enough Items 4.7.5.85
Forge Mod Loader 8.0.99.99
Minecraft Coder Pack 9.42
Better Placement 1.0.0-1

**Comment by kitsushadow** [comment]
Use the breaker

add a Gallagher

place a block of iron ore in front

charge the breaker up some amount, the amount depends on the block's
hardness and resistance

Shift + right click to discharge

**Comment by CJL48** [comment]
...oooh. I had no idea how the breaker worked until you mentioned it. Might be worth mentioning how it works on the mod website.

**Comment by CJL48** [comment]
It isn't a big thing, but recipes for the iron/cleaniron/steel slayers and iron anvil are also absent from the wiki. Though I don't know that those items can be crafted to start with.

**Comment by kitsushadow** [comment]
Yes they can be, i know they are missing. Sorry

**Comment by CJL48** [comment]
It's alright.

**Comment by RiverC** [comment]
Is it me or in the latest version, does the block breaker annihilate iron ore blocks? I'm having trouble recovering the dust.

**Comment by kitsushadow** [comment]
This is the first im hearing this. What version are you using?

Current users are using it fine
