### ISSUE TITLE
Bloomery temp keeps resetting to 1200

### ISSUE THREAD

**Issue by Thyriel** [kitsushadow/forgecraft#27]
When trying to follow your tutorial i can't get the temperature to 2000. After 1200 it keeps increasing but resets to 1200 every few seconds, so i never reach the 2k

edit: A minor glitch too: When using the stone tongs on a heated item while it already holds an item, the already holded item vanishes

**Comment by kitsushadow** [comment]
Use a higher grade charcoal.

**Comment by Thyriel** [comment]
What's a higher grade charcoal ?
