### ISSUE TITLE
Misplaced items get stuck on anvil and in bloomery

### ISSUE THREAD

**Issue by kiwifrogg** [kitsushadow/forgecraft#28]
It might just be something I can't find, however if you place a part in the wrong spot or it goes cold how do you remove it without breaking the anvil.

Same with the bloomery how do you remove charcoal or crucible if you've put them in by mistake.

**Comment by kitsushadow** [comment]
Use a shovel and right click? or shift right click to remove charcoal

Empty hand right click to remove cooled  objects

**Comment by kiwifrogg** [comment]
Does it have the be the shovel from the forge mod?  I tried a vanilla one, also I could not pick the items up with a empty hand.

**Comment by kitsushadow** [comment]
Any shovel will work just right click or shift right click. It definitely
should pull the cooled chunk off. Empty hand right click aiming at the
chuck should remove the cooled ingot

**Comment by kiwifrogg** [comment]
Still can't pull the cold item off, It is when you place a hot pick head(for example) on the anvil if it cools down it seams to be stuck, you need to break the anvil to remove it.  Also a full hot iron chunk if its not shift clicked can't be picked back up.

**Comment by kitsushadow** [comment]
Is this still a problem @kiwifrogg
