### ISSUE TITLE
braking clean iron crucible give iron dust not clean iron ingot

### ISSUE THREAD

**Issue by bdudek** [kitsushadow/forgecraft#34]
braking clean iron crucible gives iron dust, not clean iron ingot. the clean iron ingot doesn't appear in JEI aswell. V:1.4.05

**Comment by kitsushadow** [comment]
raw clean iron crucible of cooked clean iron crucible

**Comment by bdudek** [comment]
it was with the cool clean iron crucible but appond rebooting the pack it started working again and getting the ingot from it so it might have self-fixed itself I think?

**Comment by kitsushadow** [comment]
awesome, that's a relief =p
