### ISSUE TITLE
Request: copper casting and tools

### ISSUE THREAD

**Issue by WrongWeekend** [kitsushadow/forgecraft#35]
Great mod so far but I think making Chalcolithic era tools made from simple copper would be a good addition. The mod already has a copper saw, but copper axes, arrowheads, and presumably other tools have a historical background. They would be made more or less the same way as bronze, but require 4 copper inside a crucible as opposed to 3 copper and 1 tin. This would require a smaller variety of resources to produce, but the tools themselves would be somewhat weaker.

**Comment by kitsushadow** [comment]
Love the suggestion. The issue is given the accessibility of tin what is to
keep players from going straight to bronze instead of using copper first?

**Comment by WrongWeekend** [comment]
Copper tools were used first in real life due to the rarity of tin and the need to set up long-distance trade routes to acquire it. In Minecraft this would be reflected with mods for non-uniform ore generation, where copper is found in many different biomes and climates but tin deposits appear in only a select few, less common biome types such as mesa, ice plains, or jungle. Dooglamoo Worlds and BiomeTweaker are examples of such mods. Forgecraft doesn't handle copper/tin ore generation, so it would be up to players to make these choices.

Another method would be making copper tools a necessary part of acquiring bronze, such as needing a copper pickaxe to mine tin ore, copper tongs to handle a bronze crucible or a metal (copper) hammer to crush a tin ore block.

There's also the option of simply making copper tools cheaper regardless of accessibility to tin - such as a crucible for copper requiring 3 copper dust or less.

**Comment by kitsushadow** [comment]
As much as I want to support everyone. Copper tools are useless for doing anything other than moving dirt. All stone will bend the copper =/
I will add but I will put it behind a config which disables them by default.

**Comment by XvBUSHvX** [comment]
I respect and appreciate you decision.

**Comment by kitsushadow** [comment]
This feature is added with Forgecraft 1.6.15
