### ISSUE TITLE
Stone tongs, after placing failed clean iron crucibles, do not revert to empty-handed

### ISSUE THREAD

**Issue by WrongWeekend** [kitsushadow/forgecraft#36]
After using the stone tongs to remove a clean iron crucible from the bloomery that had failed, I placed the crucible on the sand. The crucible was placed, but the tongs continued to hold a failed clean iron crucible. This allowed me to place an unlimited number of the failed crucibles which could be picked up as empty ones and reused.

This did not occur with the successfully smelted clean iron crucibles.

EDIT: Also happens with failed steel crucibles. I haven't checked the others yet but I suspect it happens with them as well.

**Comment by kitsushadow** [comment]
Fixed in development
