### ISSUE TITLE
JEI not showing full crafting recipe for Tools

### ISSUE THREAD

**Issue by cScotPlay** [kitsushadow/forgecraft#38]
Current Mod Versions:
KFC: 1.4.05
PrimalCore: 1.12.2-0.6.23
JEI: 1.12.2-4.8.5.150

The tool head for all tools is not currently showing in JEI.  You are still able to craft the tool but it doesn't show the heads when searching the recipes.

**Comment by kitsushadow** [comment]
Fixed cScot. GET THAT SHIT OUTTA HERE
