### ISSUE TITLE
Suggestion/Request: Soft Crucible retexture.

### ISSUE THREAD

**Issue by rujuk** [kitsushadow/forgecraft#47]
I'm colorblind (protanopia). When i made my first soft crucible i thougth it vanished. I have to inspect every slot that looks unused until i see 3 dots/pixels that are different from rest of inventory slot color. I use vanilla texture. I was wondering if it was possible to pick a color that is not too close to vanilla inventory or give the icon an outline so it doesnt blend in with the background?

**Comment by kitsushadow** [comment]
I think this is a great suggestion, ill look into improving the texture

**Comment by kitsushadow** [comment]
I have updated the texture. Please let me know what u think. Its in the new beta release.

**Comment by rujuk** [comment]
I tried both beta and lastest release, soft crucible still looks the same which was my main problem, but i like the new fired/cooked crucible.

**Comment by kitsushadow** [comment]
Still working on this

**Comment by kitsushadow** [comment]
This should be fixed, it's an orange'ish red now

**Comment by kitsushadow** [comment]
@rujuk let me know if this looks better.

**Comment by rujuk** [comment]
I am so happy with the result. I was literally in tears when i saw the new icon. <3

**Comment by kitsushadow** [comment]
Ha, glad that helped.
