### ISSUE TITLE
Mod Version 1.0.4 listed for 1.11.2 throws error

### ISSUE THREAD

**Issue by Dragnier** [kitsushadow/forgecraft#5]
<img width="2032" alt="screen shot 2017-01-28 at 3 18 11 am" src="https://cloud.githubusercontent.com/assets/19270499/22395346/e3ce86c8-e508-11e6-93ba-6480a01d0753.png">

I installed via the Curse Launcher.

**Comment by kitsushadow** [comment]
thanks, mod version was removed

**Comment by kitsushadow** [comment]
use the most recent version to fix this

**Comment by kitsushadow** [comment]
Let me know if using the newest version works for u, if so, I'd like to close the issue

**Comment by AutisticMC** [comment]
what happen to the mod

**Comment by Dragnier** [comment]
I'm using 1.11.2, so none of your other versions work.

**Comment by kitsushadow** [comment]
hmm ya, I haven't pulled the 1.11.2 forge yet. Let me pull it and try

**Comment by kitsushadow** [comment]
@Dragnier this should be fixed in version 1.1.1 which I just uploaded a moment ago

**Comment by Dragnier** [comment]
Yep, this seems fixed now. Thanks!
