### ISSUE TITLE
Infinite resource by breaking cooked iron crucible with a pickaxe

### ISSUE THREAD

**Issue by AttilaPapp** [kitsushadow/forgecraft#53]
Get an iron filled crucible and cook it, then put in on the ground, break it with a pickaxe. You get a cooked crucible and a wrought iron back. You can put the cooked crucible back on the ground and repeat the process for infinite resource.

**Comment by kitsushadow** [comment]
should be fixed with 1.6.03
Please report if it is.

**Comment by kitsushadow** [comment]
fixed
