### ISSUE TITLE
[1.6beta] Adding charcoal to a bloomery with charcoal in it consumes too much

### ISSUE THREAD

**Issue by darthvader45** [kitsushadow/forgecraft#54]
I right click my bloomery, it says it has 55 charcoal in it, and I assume the max it can hold is 64.  So I go and get a stack of high-grade charcoal, matching what is in the bloomery already, and right click the bloomery with it.  It then proceeds to eat the whole stack, and yet shows it is full again at 64.  It should have only taken 9, and left 55 charcoal in my inventory.

**Comment by kitsushadow** [comment]
I can't replicate this. I added charcoal that would have added up to more than 64 and was left with remainder in my hand.
