### ISSUE TITLE
Brick bloomery and Crucible crash

### ISSUE THREAD

**Issue by TPC25** [kitsushadow/forgecraft#56]
Using Forgecraft v: 1.6.11

Just wanted to report a crash with the Crucible being inside the Brick Bloomery. What happen was I was learning to use this for the first time and I couldn't figure out how to add the iron ore in the cruible, so I thought maybe I had to place the crucible in the bloomery first then toss the ore into it, didn't work so when I took the stone tong and right click to pull it out, I got the first crash here:  https://pastebin.com/bq04THQW

After that crash, I started the game back up and  then I get this crash when trying to enter the world: https://pastebin.com/Am9ab7Mr

I had to delete the world because it kept doing it over and over. Not a problem, all this is testing anyway because I wanted to help and make sure everything works good before starting the real world. I figure it out afterward, it's work fine, just wanted to report that we can't place the crucible in the bloomery without an ore in it or we will get the crash

**Comment by TPC25** [comment]
Not yet but I can join

**Comment by TPC25** [comment]
Ok, I'm in there but saids I don't have permission to see chat or anything. Also, I figure it out but now I see another problem, when I put the crucible on the stone anvil, the block doesn't render on it

**Comment by kitsushadow** [comment]
You don't put the crucible on the stone anvil

**Comment by kitsushadow** [comment]
fixed
