### ISSUE TITLE
Crash with JEI in Forgecraft-1.6.15

### ISSUE THREAD

**Issue by AttilaPapp** [kitsushadow/forgecraft#58]
On the official server in JEI go to the stone anvil recipes, find repair clean iron recipe and hover over the pickaxe head = instant crash

**Comment by kitsushadow** [comment]
I'm pushing a change for this but it means that you will NOT be able to see NBT requirements for for inputs. Fking JEI. I had this issue before. JEI doesn't like how Tool NBT is managed.

Build 1.6.17 should have a fix for this.

**Comment by kitsushadow** [comment]
In a future update i will make so the tool part is the only piece that will not show its NBT. Unfortunate but better than nothing.

**Comment by kitsushadow** [comment]
This should be fixed with .20
