### ISSUE TITLE
Loads in single player but crashes on dedicated server 

### ISSUE THREAD

**Issue by yujukitten** [kitsushadow/forgecraft#6]
[crash-2017-02-20_12.34.30-server.txt](https://github.com/kitsushadow/forgecraft/files/788292/crash-2017-02-20_12.34.30-server.txt)

Here is the crash log I received today after successfully loading into single player, when I tried to load it on the dedicated server. I am new  to all this and really don't understand what it means by " Caught an exception"

**Comment by kitsushadow** [comment]
This is fixed, thanks for reporting the issue
