### ISSUE TITLE
Crash on Start up

### ISSUE THREAD

**Issue by BSKCorp** [kitsushadow/forgecraft#7]
Just got around to finally updating the modpack of mine and give it a try and it crashed right on start up.

Crash Log - https://pastebin.com/CTVxBRfC

I also just updated MoreFurnaces so I am going to remove that and see if it loads., So far that is the only thing I can think of and will update the issue if there is a compatibility problem.

**Comment by kitsushadow** [comment]
What version of Minecraft are u running?

**Comment by BSKCorp** [comment]
Sorry - 
MC 1.11.2
Forge Version 1.11.2-13.20.0.2253
Mod version 1.2.03

**Comment by kitsushadow** [comment]
What Version of Primal is loaded?

**Comment by BSKCorp** [comment]
None... lol

**Comment by BSKCorp** [comment]
I take it, it is a dependency?

**Comment by kitsushadow** [comment]
yes, been trying to mark that in all the places i can. Technically Forge should tell u instead of having everything crash.

**Comment by BSKCorp** [comment]
XD OK well that would explain it then, Guess it's time to try yet another new mod haha.

**Comment by kitsushadow** [comment]
=) If you have questions join us here

https://discord.gg/QDrRGyR
