### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by infernominer601** [kitsushadow/forgecraft#9]
for my issue there is alought of content missing

**Comment by kitsushadow** [comment]
from 1.10.2?

If that is the version u are using i will not be back porting content to 1.10.2
With 1.12 around the corner i will barely have the time to complete the content i want b4 supporting 1.12 and 1.11 versions

**Comment by infernominer601** [comment]
to 1.7.10

**Comment by infernominer601** [comment]
didnt know there was a 1.10.2

**Comment by infernominer601** [comment]
for that mod will check into it thx for telling me
